version: "3.7"

services:
  testdatagenerator:
    build:
      .
  volumes:
    - ./config:/opt/testdata-generator/src/config
    - ./input:/opt/testdata-generator
    - ./output:/opt/testdata-generator
